---
- hosts: mailserver
  remote_user: admin
  become: yes
  become_method: sudo
  vars_files:
  - "./vars/variables.yml"

  tasks:
#Puedo incluir variables usando el módulo include_vars
#  - name: Include variables for tasks and templates
#    include_vars:
#      file: variables.yml

  - name: Epel repo estan instalados
    yum:
      name: epel-release
      state: present 

  - name: Instalar paquetes
    yum:
      name: "{{ packages}}"
      state: latest

  - name: Escribiendo configuracion postfix
    template:
      src: ./templates/postfix-main.j2
      dest: /etc/postfix/main.cf
    notify:
    - restart postfix

  - name: Asegurarse de que postfix esta corriendo
    service:
      name: postfix
      state: started
      enabled: yes
      
  - name: Habilitar imap en dovecot
    lineinfile:
      path: /etc/dovecot/dovecot.conf
      line: 'protocols= imap pop3 lmtp'

  - name: Copiar configuracion de mail en dovecot
    copy: 
      src: ./10-mail.conf
      dest: /etc/dovecot/conf.d/10-mail.conf
    notify: 
    - restart dovecot

   - name: Dovecot corriendo y habilitado
    service:
      name: dovecot
      state: started
      enabled: true

  - name: Configurar squirrelmail
    template:
      src: ./squirrelmail.conf.j2
      dest: /etc/squirrelmail/config.php
      owner: root
      group: root
      mode: 0640

  - name: Apache corriendo y habilitado
    service:
      name: httpd
      state: started
      enabled: true
      
  - name: puertos abiertos en firewall       
    firewalld:
      service: "{{item}}"
      state: enabled
      permanent: yes
      immediate: yes
    loop:
    - smtp
    - imap
    - http

  handlers: 
  - name: Reiniciar postfix
    service:
      name: postfix
      state: restarted
      enabled: yes 

  - name: Reiniciar dovecot
    service:
      name: dovecot
      state: restarted
      enabled: yes   

